<!-- +++++ Posts Lists +++++ -->
    <div id="white">
	    <div class="container">
			<div class="row">
				<div class="col-lg-8 col-lg-offset-2">
					<p><img src="<?php echo base_url();?>assets/img/me.jpg" width="50px" height="50px"> <ba>Agustin Baretto</ba></p>
					<p><bd>Monday, March 02, 2015</bd></p>
					<h4>Failure: Understanding and Accepting the Risk</h4>
					<p>We all fear failure; it’s natural for human beings. We all want to win, be the successful guy on the cover of the magazine, get to the top without any bruises or scars. But nobody wants to fail. This is why people hate to make decisions, because they might lead to failure. Not to mention risks: risks are the prophecy of failure, a detailed description of how things might go wrong and how illusions might crumble while trying to get a greater reward. No one likes to make decisions, no one likes to take risks… except for entrepreneurs!</p>
					<p>Entrepreneurs know their chances of failing are greater than those of succeeding, but still they try and risk their time and money. We’ve all heard the encouraging phrases from Hollywood, like, “if you build it they will come” or “all you need is a good idea and money will roll in,” but unfortunately that is not the truth. Real entrepreneurs work hard, and fail. They have lost the ball many times, but have learned how to “pivot” and adapt to change. We are used to hiding our failures, because we think we should be ashamed of them. Kids hide their exams when they get an F. People try not to talk about their ex-lovers during dates. But entrepreneurs are different. They like to talk about their failures and share their experiences with others, and considering myself an entrepreneur, I am going to tell you about my biggest startup failure…</p>
					<p>Back in 2006 when social networks were starting to become popular, a friend of mine and I created a social network oriented to fashion hunters (Fashionism). It basically relied on users uploading pictures of other people they saw on the street who were nicely dressed, which were then liked and commented on by others. Users could even customize their profiles in a sort of MySpace way by selecting their palettes and background images. The monetization model consisted of letting brands have special accounts that could post videos, have tailored styles for their profiles, and charge them for advertising as well.</p>
					<p>Unfortunately technologies were a little bit behind us at that time. Smartphones did not even exist yet, digital cameras were not as accessible as today, and even those who had them would not go out on the street and start deliberately taking pictures of people. Social networks did not have open APIs either, so we could not make use of their existing social graphs to share the app and reach other people. Users could only invite their friends by sending emails to them! (It was one year before <a href="http://techcrunch.com/2007/05/24/facebook-launches-facebook-platform-they-are-the-anti-myspace/" target="_blank">this</a>).</p>
					<p>On the other hand, we were young and had no experience, and we were self-centered. We just worried about the code and underestimated the need for advertising, marketing and PR. People did not follow the site’s premise and instead uploaded pictures of themselves on holidays, at birthday parties or doing any other thing. We were angry with them because they had gotten it wrong, but we were the ones who got it wrong.</p>
					<p>We waited to launch our product until we felt it was ready (this was more than six months), but we never spent any time asking the users what they wanted, because we thought we knew what they wanted. “Lean development” did not ring a bell to us yet. “Virality” was the hype term instead, and we just thought that “if we built it, they would come”. We did not have a coach or mentor who told us what steps to take, what to do and what not do, so we had to learn by hitting the wall. It was a very sad moment for us when we decided to turn off the lights.</p>
					<p>Fashionism was a complete failure. Still, we are proud of it. We gave our best and learned a lot. We could take more punches after that. We are not afraid of failing anymore because we know it is not the end of the world. It is just a stage we needed to go through before we could become adults in the world of entrepreneurship.</p>
				</div>

			</div><!-- /row -->
	    </div> <!-- /container -->
	</div>
	
	<div id="grey">
	    <div class="container">
			<div class="row">
				<div class="col-lg-8 col-lg-offset-2">
					<p><img src="<?php echo base_url();?>assets/img/me.jpg" width="50px" height="50px"> <ba>Agustin Baretto</ba></p>
					<p><bd>Monday, March 02, 2015</bd></p>
					<h4>The World of Human-Computer Interaction</h4>
					<p>I will dedicate this post to talking about what HCI is and what kind of research takes place in this area. Human-Computer Interaction is a relatively new field within computer science based on the study and design of interfaces between users and systems. These can range from websites and information layout to devices such as screens, wearable technologies, robot communication and even accessibility designs for disabled users. HCI not only requires classical computer science knowledge (programming, databases, networks) but also intersects with many softer areas such as psychology, sociology, cognitive sciences and media studies.</p>
					<p>In the beginning, everything was about “making it work”. Users had to adapt to the computer and not the other way around. The programmer had already spent too much time working on complex software to add a bunch of “usability” requirements on top of that, just to make it look nicer (Don’t get me wrong, this is not me speaking! It’s just the answer you would have probably received from a programmer in the ‘90s if you had asked him to change his COBOL-software because users could not figure out how to use it).</p>
					<p>Fortunately, things changed with time and though IT geeks remain quite sensitive to comments about their code and interfaces (myself included), new roles such as designers, UX (User Experience) designers, product managers and business analysts have gained more importance in the software development cycle. These people can basically put themselves in the shoes of a non-technical user and think how the system could be improved in order to be more intuitive and need almost no help, nor textual references to understand it. No wonder children can just sit in front of a tablet and slide their fingers like pros after only a few hours of practice. Things are easy now; common sense rules and interfaces imitate reality. HCI is the main factor responsible for this revolution and much of the comfort and ease we find in today’s interfaces would not exist if it hadn’t been for years of research devoted to this field. Pinching, dragging, and touching appear to be magical in comparison to old-school clicks, tabs and enters!</p>
					<p>HCI research tries to go one step beyond and study how things will be in the coming years. For example, interfaces have been proven to help teach body language to children with autism – not to replace traditional human tutoring and attention, but as a way to complement it (and even supplement it in extreme cases such as inhabitants of poor countries or remote places).</p>
					<p>During the upcoming months I will have the good fortune to work with Dr. Ehsan Hoque, a renowned expert in the field, in the study of interactions between humans and computer-based systems to improve communication skills. There is not much I can say as most of our research is still in progress, but I can leave one question open which I hope I will be able to answer by the end of this semester: can a person improve his public speaking by receiving live feedback from a computer?</p>
				</div>

			</div><!-- /row -->
	    </div> <!-- /container -->
	</div>
	
	<div id="white">
	    <div class="container">
			<div class="row">
				<div class="col-lg-8 col-lg-offset-2">
					<p><img src="<?php echo base_url();?>assets/img/me.jpg" width="50px" height="50px"> <ba>Agustin Baretto</ba></p>
					<p><bd>Friday, May 8, 2015</bd></p>
					<h4>Diving into Data Mining</h4>
					<p>As part of the TEAM program, students are encouraged to take up to three technical elective courses. This is a perfect complement to the core entrepreneurship management courses as it allows us to get in touch with the latest technologies available and focus on those specific areas that might be needed to develop our future startups. In my case, coming from a Computer Science background and being deeply interested in the creation of web and mobile apps, I decided to take Data Mining and Human Computer Interaction courses during the past semester. I can say today, that my decision could not have been more accurate. I learnt a lot from both courses and more important, I was able to put my knowledge into practice by working on small projects required by them. On top of that, after finishing the semester, I was asked by both professors to do research for each of the courses, so that means I will be able to further dive into the stuff I love and will have plenty of time to do it!</p>
					<p>On this post, I am going to talk about Data Mining and will leave HCI for my next article. Data Mining is the extraction of interesting patterns within large sets of data by using several different techniques related to Artificial Intelligence, Statistics, Machine Learning and Database Systems. These patterns are then translated into useful information that can be easily understood by end users or clients. So for example, a supermarket might use DM in order to analyze its customers purchases and make smart decisions based on the results of the research. These might help to understand what different kinds of customers shop at the supermarket, what they seek, how much they spend on average, and what products they usually buy. It might also help to find correlations between products (like most of the customers that buy gin also buy tonic and lemons). Or even to predict whether putting a new product on a specific shelve would be a good decision or if it should be put somewhere else. There is known myth that says that Wal-Mart found years ago that many young american male bought diapers and beer, something not obvious at first sight and not expected to happen. You would expect customers buying diapers to also buy baby food for example, but not beer. After doing some analysis, researchers reached to the conclusion that these were young new fathers that were asked by their wives to go out buy some diapers and once they were at the shop took the chance to also get some beer!</p>
					<p>There is plenty of bibliography about this fascinating discipline you can read so I will stop talking about Data Mining and tell you about the project I worked on during the end of the course. Christmas was coming and I wanted to give a book as a gift to a friend and so I faced the problem: what books would this friend like? Gustame is an app I developed to address this problem. By signing in to the site using their Facebook account, users are able to see a list of their friends and for each of those friends, get recommendations based on the Facebook Pages related to books they already liked. Sounds tricky huh? Then I should not mention that it uses an open knowledge database (Freebase) to disambiguate redundant entities and that it uses a Slope One algorithm based on your closed graph of contacts to do the recommendation… but I will give you an example so you can figure out how it works:</p>
					<p>-Your friend Albert has liked the Facebook the pages “The Hobbit - the book” and “Alice in Wonderland”, so we might assume he has read those two books.</p>
					<p>-Your other friends Bob and Claire also liked those two pages and they also liked “The Narnia Chronicles Book”, which Albert hasn’t. This means they have similar taste to Albert and that they have read a book Albert might enjoy reading too.</p>
					<p>-You get a recommendation to give Albert the book “Narnia Chronicles” as a gift.</p>
					<p>However, I invite you to just go and try the app by yourself by clicking <a href="<?=site_url('main') ?>" target="_blank">here</a>! Any suggestions are welcome ;)</p>
				</div>

			</div><!-- /row -->
	    </div> <!-- /container -->
	</div>
	
	<!-- +++++ First Post +++++ -->
	<div id="grey">
	    <div class="container">
			<div class="row">
				<div class="col-lg-8 col-lg-offset-2">
					<p><img src="<?php echo base_url();?>assets/img/me.jpg" width="50px" height="50px"> <ba>Agustin Baretto</ba></p>
					<p><bd>Monday, December 22, 2014</bd></p>
					<h4>Things to do in Life</h4>
					<p>Plant a tree, have a child, write a book, and win a pie-eating contest. That is the list of things that, in my humble opinion, every man should do in order to ensure a measure of immortality. Luckily I can say I have already done the last one. Coincidentally, I accomplished it during Thanksgiving week. Here’s the story:</p>
					<p>To be honest, I had never celebrated Thanksgiving before in my life, so I was new to the whole cranberry and turkey dinner thing. I didn’t know much about what was being celebrated so in my eyes, it all looked like a second fall break (only this time, there were Black Friday offers in the middle). Shops and advertisers had long ago started shooting their fall artillery by decorating every single corner of the city with pumpkins and autumn leaves, and e-commerce websites were counting the days before the big sales started. I did not have anything against it, but I felt that Thanksgiving had to be something more than just people queuing outside stores, waiting to get inside to get the best deals like I had seen on TV in previous years. And I was right.</p>
					<p>Not long before the holiday, I received an email from Simon Business School inviting students to get together to enjoy a Thanksgiving dinner. There was going to be turkey and stuffing, and even vegetarian turkey for those who don’t eat meat. Everyone was invited to have a good time, and that was the only important thing. I decided to go and leave my prejudices behind. Maybe it was not just a commercial thing like I thought, and if these people were inviting me just because, then there had to be a reason to celebrate.</p>
					<p>When I got there, I couldn’t have been happier with my decision. Everyone at the party was friendly and amicable. People were introducing each other and talking about their projects and dreams, their pasts and futures. Organizers were joyfully serving typical Thanksgiving dishes and explaining how they were prepared, what ingredients were in them, and even telling stories about how they used to celebrate when they were children. It did not seem like a marketing campaign or a fashionable trend. These people’s eyes were shining as they remembered the way their mothers used to prepare the same foods for them or how their fathers took them to see a football game at this time of year. Thanksgiving seemed to be deeply rooted in these people’s lives, a cultural, historical and, for some, even religious occasion to give thanks for what they had by serving others – something we should all imitate and do, whatever our creed is, wherever we come from.</p>
					<p>It was while I was under this state of Thanksgiving excitement, and inspired by this excessive amount of contagious happiness, that I decided to sign myself up for a pie-eating contest. When in Rome… do as the Americans do… and so I did. I was going to do my best, I was going to be part of the celebration too, and just as others had cooked or laid the table, my role now was to eat that pie and show my gratitude to this University that had opened its arms to me.</p>
					<p>Ready… Set… Go! I smashed my face into the pie and started taking the biggest bites I could, while my cheeks and forehead were totally covered in pumpkin and cream! Time was running out and I had to devour this pie and… well, then someone told me I could use a spoon, like the rest of the participants. I had thought it was the kind of contest where people can’t use their hands (like the ones you see on TV) but it did not matter. I was a little surprised and embarrassed but I continued until my plate was empty. The end of the story is: I won the contest! But even better, I got the best of all prizes: an evening surrounded by nice people that I will always remember with a smile on my face.</p>
				</div>

			</div><!-- /row -->
	    </div> <!-- /container -->
	</div><!-- /grey -->
	
	<!-- +++++ Second Post +++++ -->
	<div id="white">
	    <div class="container">
			<div class="row">
				<div class="col-lg-8 col-lg-offset-2">
					<p><img src="<?php echo base_url();?>assets/img/me.jpg" width="50px" height="50px"> <ba>Agustin Baretto</ba></p>
					<p><bd>Monday, November 24, 2014</bd></p>
					<h4>Being a Part of the NYC Swing</h4>
					<p>Weekend trips are a great way to travel and visit new places you might have always wanted to see, while at the same time staying relatively close to home and campus so as to quickly get back to studying without the hassle of flight connections, passports, jet lag and excess baggage fees. Just grab a backpack and fill it with as many clothes as you can, and that is all you need to start rollin’ down the road. Fall is the perfect time to take a break, especially after finishing midterms, so why not take a bus and head to the big city? That’s what I decided to do last weekend. Here are some of the tips I can share with you from my experience as a tourist in New York City:</p>
					<p>Getting there: Priceline.com offers really good deals if you are not in a hurry (you can even bid for flight tickets by “naming your price” with the condition that you cannot pick a specific time to fly but only the date you expect to do it). I really wanted to make the most out of my time though, so I decided to travel by bus overnight: I just boarded, sat in my seat, closed my eyes, and when I opened them again I was waking up in the city that never sleeps!</p>
					<p>Accommodations: Even though New York has a lot of hotels and hostels to accommodate the thousands of tourists that usually visit the city, it can sometimes be tricky to find a place to spend your weekend, and even trickier if, like me, you did not plan your trip with much time in advance. Luckily, there are people willing to rent their furnished apartments in great locations for only a few days at incredible prices. Sites like Airbnb.com allow you to get in touch with them and assure a safe experience to both owners and visitors.</p>
					<p>Shopping: New York City has a wide variety of shops to offer, from large renowned stores to small independent vintage-style shops. I was traveling with my girlfriend, so I can assure you – I have visited most of them (if not all).</p>
					<p>Instagram it! If there is a place to take cool pictures with vintage effects, it is New York City. The views from Top of the Rock and the Empire State Building, the Statue of Liberty, and the bridges are some of the photos you MUST take and share with your friends and relatives, so prepare your camera and create an account for any social network you like.</p>
					<p>Art, art, art: I spent three days in the city, and one of them was dedicated solely to art. It all started at the Museum of Modern Art (they offer free visits on the first Friday of the month), with a lucky and unexpected viewing of the Henri de Toulouse-Lautrec exhibit (in place until March 2015). Then I continued to the Guggenheim (with a building that is a work of art itself), and concluded with a visit to the New York Comic Con (the greatest comic and entertainment expo in the world). Whatever type of art you are most excited about, New York will have a gallery or museum to engage you.</p>
					<p>Eat and drink: There are plenty of bars and restaurants to visit in New York, and most of them can be found in any travel guide, but there is a place I discovered that you will probably not read about unless someone tells you about it. It is a bar called 230 FIFTH (named for its location at 230 Fifth Avenue) and it is located on the rooftop of a building with a perfect view of the city. Either for a brunch at noon or an evening drink, this place will make you feel you are actually on top of the world. There are no signs outside so just walk into the building, head to the elevator and press the rooftop button!</p>
					<p>Getting around: Fall is a wonderful time to visit New York, whether you enjoy strolling through colorful parks or heading inside to warm up to some vibrant entertainment. But whatever you choose, you will definitely need to be prepared to walk. Even though the city has an affordable and convenient transportation service (with extensive subway and bus systems), it will sometimes be quicker for you to just travel around using your feet, and it will also allow you to get to know the city better. Another option for those who are more adventurous is to hop onto a bike and cruise along the many bike routes the city has.</p>
					<p>All in all, I enjoyed traveling to this marvelous and exciting city. Although I was really tired after the weekend and really wanted to get back to good old Rochester, I must say I had a great time there and had the chance to discover very nice places and people (New Yorkers are one-of-a-kind, friendly, open-minded and humorous). The beauty of the buildings and parks appealed to me. I was touched by my visit to the 9/11 Memorial Museum and could not avoid thinking how much more beautiful it would have looked if the towers were still there. New York is definitely a place to visit and luckily, it is very close to Rochester!</p>
				</div>

			</div><!-- /row -->
	    </div> <!-- /container -->
	</div><!-- /white -->
	
	<!-- +++++ Third Post +++++ -->
	<div id="grey">
	    <div class="container">
			<div class="row">
				<div class="col-lg-8 col-lg-offset-2">
					<p><img src="<?php echo base_url();?>assets/img/me.jpg" width="50px" height="50px"> <ba>Agustin Baretto</ba></p>
					<p><bd>Tuesday, October 28, 2014</bd></p>
					<h4>Just Like in the Movies</h4>
					<p>Just like in movies…</p>
					<p>I think that is the best way to summarize my experience so far, since the very first moment I stepped foot onto the University of Rochester campus.</p>
					<p>Things I had seen all through my childhood on television suddenly became real experiences I was able to witness and feel with my own senses. Images I thought were just the product of the film-making industry happened to actually be true and tangible. A “just like in the movies” University!</p>
 					<p>There’s the majestic English-style buildings with lots of students coming in and out, the state of the art labs with guys carefully holding test tubes, the eat-as-much-as-you-want cafeteria with students holding trays with burgers, salad, and milk (you definitely would not mix that food and beverage where I come from…), the American football team with more players on the sidelines than playing (sorry, I just can’t understand this game… believe me I tried!), the guy watching them eating an enormous hotdog and drinking from a massive jumbo Pepsi. There were the first-day-of-classes, events with games, bands playing, free T-shirts, and the fraternity parties (not that I have gone to any yet… I just heard about them). There’s the vast, monumental quad with the greenest grass you could ever see (believe me, it’s so green you need sunglasses to walk through it), and the group of guys playing frisbee – don’t ask me why, but you will always find them, a group of happy people laughing and graciously jumping trying to catch the frisbee in the air (when do they study, I ask myself whenever I see them), while I focus on making it from one class to the other, worrying about the assignments that still need work.</p>
					<p>I could even say my life outside of campus has become a little bit like the lives of movie characters: I wake up in the morning, have some just-like-in-movies (JLIM) breakfast (coffee, orange juice, pancakes, eggs & bacon) walk down a street full of JLIM typical American houses with a JLIM large front yard, a JLIM porch with some chairs, a JLIM 2-cars-wide garage, and (of course) a JLIM mailbox with the family name on it on the street. I could probably go on naming JLIM things, but I think you get the point… many things are just the way I used to picture them before coming here. But there are also many things I deal with everyday that do not appear on the movies: there are lots of assignments, hard work to do, exams to study for. There are great professors and advisors willing to help you and give you their advice at any time, even after class. There are lots of resources for students such as printers, private offices to study in and nice, smiling librarians at our disposal to help us find whatever piece of information we need. There are the offices for international students and for career services, both of which organize meetings to make us feel at home. There are also talks and dissertation paper defenses and job fairs. There are even complex math discussions with random people at a bus stop (maybe that would fall into the just-like-in-Big-Bang-Theory things…)</p>
					<p>To sum up, some things are just like in the movies, others not. Some days I love it here, other days I miss where I’m from. Some things are very cool, some are not. Some things are really fun, some not so much. Some things are really easy, some things definitely aren’t. Some days go really quickly, some move rather slowly. Now that I think about it… things are just like back home.</p>
				</div>

			</div><!-- /row -->
	    </div> <!-- /container -->
	</div><!-- /grey -->