<!-- +++++ Posts Lists +++++ -->
	<!-- +++++ First Post +++++ -->
	<div id="grey">
	    <div class="container">
			<div class="row">
				<div class="col-lg-8 col-lg-offset-2">
					<p><img src="<?php echo base_url();?>assets/img/me.jpg" width="50px" height="50px"> <ba>Agustin Baretto</ba></p>
					<p><bd>Monday, December 22, 2014</bd></p>
					<h4>Things to do in Life</h4>
					<p>Plant a tree, have a child, write a book, and win a pie-eating contest. That is the list of things that, in my humble opinion, every man should do in order to ensure a measure of immortality. Luckily I can say I have already done the last one. Coincidentally, I accomplished it during Thanksgiving week. Here’s the story:</p>
					<p>To be honest, I had never celebrated Thanksgiving before in my life, so I was new to the whole cranberry and turkey dinner thing. I didn’t know much about what was being celebrated so in my eyes, it all looked like a second fall break (only this time, there were Black Friday offers in the middle). Shops and advertisers had long ago started shooting their fall artillery by decorating every single corner of the city with pumpkins and autumn leaves, and e-commerce websites were counting the days before the big sales started. I did not have anything against it, but I felt that Thanksgiving had to be something more than just people queuing outside stores, waiting to get inside to get the best deals like I had seen on TV in previous years. And I was right.</p>
					<p>Not long before the holiday, I received an email from Simon Business School inviting students to get together to enjoy a Thanksgiving dinner. There was going to be turkey and stuffing, and even vegetarian turkey for those who don’t eat meat. Everyone was invited to have a good time, and that was the only important thing. I decided to go and leave my prejudices behind. Maybe it was not just a commercial thing like I thought, and if these people were inviting me just because, then there had to be a reason to celebrate.</p>
					<p>When I got there, I couldn’t have been happier with my decision. Everyone at the party was friendly and amicable. People were introducing each other and talking about their projects and dreams, their pasts and futures. Organizers were joyfully serving typical Thanksgiving dishes and explaining how they were prepared, what ingredients were in them, and even telling stories about how they used to celebrate when they were children. It did not seem like a marketing campaign or a fashionable trend. These people’s eyes were shining as they remembered the way their mothers used to prepare the same foods for them or how their fathers took them to see a football game at this time of year. Thanksgiving seemed to be deeply rooted in these people’s lives, a cultural, historical and, for some, even religious occasion to give thanks for what they had by serving others – something we should all imitate and do, whatever our creed is, wherever we come from.</p>
					<p>It was while I was under this state of Thanksgiving excitement, and inspired by this excessive amount of contagious happiness, that I decided to sign myself up for a pie-eating contest. When in Rome… do as the Americans do… and so I did. I was going to do my best, I was going to be part of the celebration too, and just as others had cooked or laid the table, my role now was to eat that pie and show my gratitude to this University that had opened its arms to me.</p>
					<p>Ready… Set… Go! I smashed my face into the pie and started taking the biggest bites I could, while my cheeks and forehead were totally covered in pumpkin and cream! Time was running out and I had to devour this pie and… well, then someone told me I could use a spoon, like the rest of the participants. I had thought it was the kind of contest where people can’t use their hands (like the ones you see on TV) but it did not matter. I was a little surprised and embarrassed but I continued until my plate was empty. The end of the story is: I won the contest! But even better, I got the best of all prizes: an evening surrounded by nice people that I will always remember with a smile on my face.</p>
				</div>

			</div><!-- /row -->
	    </div> <!-- /container -->
	</div><!-- /grey -->
	
	<!-- +++++ Second Post +++++ -->
	<div id="white">
	    <div class="container">
			<div class="row">
				<div class="col-lg-8 col-lg-offset-2">
					<p><img src="<?php echo base_url();?>assets/img/me.jpg" width="50px" height="50px"> <ba>Agustin Baretto</ba></p>
					<p><bd>Monday, November 24, 2014</bd></p>
					<h4>Being a Part of the NYC Swing</h4>
					<p>Weekend trips are a great way to travel and visit new places you might have always wanted to see, while at the same time staying relatively close to home and campus so as to quickly get back to studying without the hassle of flight connections, passports, jet lag and excess baggage fees. Just grab a backpack and fill it with as many clothes as you can, and that is all you need to start rollin’ down the road. Fall is the perfect time to take a break, especially after finishing midterms, so why not take a bus and head to the big city? That’s what I decided to do last weekend. Here are some of the tips I can share with you from my experience as a tourist in New York City:</p>
					<p>Getting there: Priceline.com offers really good deals if you are not in a hurry (you can even bid for flight tickets by “naming your price” with the condition that you cannot pick a specific time to fly but only the date you expect to do it). I really wanted to make the most out of my time though, so I decided to travel by bus overnight: I just boarded, sat in my seat, closed my eyes, and when I opened them again I was waking up in the city that never sleeps!</p>
					<p>Accommodations: Even though New York has a lot of hotels and hostels to accommodate the thousands of tourists that usually visit the city, it can sometimes be tricky to find a place to spend your weekend, and even trickier if, like me, you did not plan your trip with much time in advance. Luckily, there are people willing to rent their furnished apartments in great locations for only a few days at incredible prices. Sites like Airbnb.com allow you to get in touch with them and assure a safe experience to both owners and visitors.</p>
					<p>Shopping: New York City has a wide variety of shops to offer, from large renowned stores to small independent vintage-style shops. I was traveling with my girlfriend, so I can assure you – I have visited most of them (if not all).</p>
					<p>Instagram it! If there is a place to take cool pictures with vintage effects, it is New York City. The views from Top of the Rock and the Empire State Building, the Statue of Liberty, and the bridges are some of the photos you MUST take and share with your friends and relatives, so prepare your camera and create an account for any social network you like.</p>
					<p>Art, art, art: I spent three days in the city, and one of them was dedicated solely to art. It all started at the Museum of Modern Art (they offer free visits on the first Friday of the month), with a lucky and unexpected viewing of the Henri de Toulouse-Lautrec exhibit (in place until March 2015). Then I continued to the Guggenheim (with a building that is a work of art itself), and concluded with a visit to the New York Comic Con (the greatest comic and entertainment expo in the world). Whatever type of art you are most excited about, New York will have a gallery or museum to engage you.</p>
					<p>Eat and drink: There are plenty of bars and restaurants to visit in New York, and most of them can be found in any travel guide, but there is a place I discovered that you will probably not read about unless someone tells you about it. It is a bar called 230 FIFTH (named for its location at 230 Fifth Avenue) and it is located on the rooftop of a building with a perfect view of the city. Either for a brunch at noon or an evening drink, this place will make you feel you are actually on top of the world. There are no signs outside so just walk into the building, head to the elevator and press the rooftop button!</p>
					<p>Getting around: Fall is a wonderful time to visit New York, whether you enjoy strolling through colorful parks or heading inside to warm up to some vibrant entertainment. But whatever you choose, you will definitely need to be prepared to walk. Even though the city has an affordable and convenient transportation service (with extensive subway and bus systems), it will sometimes be quicker for you to just travel around using your feet, and it will also allow you to get to know the city better. Another option for those who are more adventurous is to hop onto a bike and cruise along the many bike routes the city has.</p>
					<p>All in all, I enjoyed traveling to this marvelous and exciting city. Although I was really tired after the weekend and really wanted to get back to good old Rochester, I must say I had a great time there and had the chance to discover very nice places and people (New Yorkers are one-of-a-kind, friendly, open-minded and humorous). The beauty of the buildings and parks appealed to me. I was touched by my visit to the 9/11 Memorial Museum and could not avoid thinking how much more beautiful it would have looked if the towers were still there. New York is definitely a place to visit and luckily, it is very close to Rochester!</p>
				</div>

			</div><!-- /row -->
	    </div> <!-- /container -->
	</div><!-- /white -->
	
	<!-- +++++ Third Post +++++ -->
	<div id="grey">
	    <div class="container">
			<div class="row">
				<div class="col-lg-8 col-lg-offset-2">
					<p><img src="<?php echo base_url();?>assets/img/me.jpg" width="50px" height="50px"> <ba>Agustin Baretto</ba></p>
					<p><bd>Tuesday, October 28, 2014</bd></p>
					<h4>Just Like in the Movies</h4>
					<p>Just like in movies…</p>
					<p>I think that is the best way to summarize my experience so far, since the very first moment I stepped foot onto the University of Rochester campus.</p>
					<p>Things I had seen all through my childhood on television suddenly became real experiences I was able to witness and feel with my own senses. Images I thought were just the product of the film-making industry happened to actually be true and tangible. A “just like in the movies” University!</p>
 					<p>There’s the majestic English-style buildings with lots of students coming in and out, the state of the art labs with guys carefully holding test tubes, the eat-as-much-as-you-want cafeteria with students holding trays with burgers, salad, and milk (you definitely would not mix that food and beverage where I come from…), the American football team with more players on the sidelines than playing (sorry, I just can’t understand this game… believe me I tried!), the guy watching them eating an enormous hotdog and drinking from a massive jumbo Pepsi. There were the first-day-of-classes, events with games, bands playing, free T-shirts, and the fraternity parties (not that I have gone to any yet… I just heard about them). There’s the vast, monumental quad with the greenest grass you could ever see (believe me, it’s so green you need sunglasses to walk through it), and the group of guys playing frisbee – don’t ask me why, but you will always find them, a group of happy people laughing and graciously jumping trying to catch the frisbee in the air (when do they study, I ask myself whenever I see them), while I focus on making it from one class to the other, worrying about the assignments that still need work.</p>
					<p>I could even say my life outside of campus has become a little bit like the lives of movie characters: I wake up in the morning, have some just-like-in-movies (JLIM) breakfast (coffee, orange juice, pancakes, eggs & bacon) walk down a street full of JLIM typical American houses with a JLIM large front yard, a JLIM porch with some chairs, a JLIM 2-cars-wide garage, and (of course) a JLIM mailbox with the family name on it on the street. I could probably go on naming JLIM things, but I think you get the point… many things are just the way I used to picture them before coming here. But there are also many things I deal with everyday that do not appear on the movies: there are lots of assignments, hard work to do, exams to study for. There are great professors and advisors willing to help you and give you their advice at any time, even after class. There are lots of resources for students such as printers, private offices to study in and nice, smiling librarians at our disposal to help us find whatever piece of information we need. There are the offices for international students and for career services, both of which organize meetings to make us feel at home. There are also talks and dissertation paper defenses and job fairs. There are even complex math discussions with random people at a bus stop (maybe that would fall into the just-like-in-Big-Bang-Theory things…)</p>
					<p>To sum up, some things are just like in the movies, others not. Some days I love it here, other days I miss where I’m from. Some things are very cool, some are not. Some things are really fun, some not so much. Some things are really easy, some things definitely aren’t. Some days go really quickly, some move rather slowly. Now that I think about it… things are just like back home.</p>
				</div>

			</div><!-- /row -->
	    </div> <!-- /container -->
	</div><!-- /grey -->